services:
  main:
    build: 
      context: .
      dockerfile: main/Dockerfile
      args:
        - PYPROJECT_TOML_PATH=../pyproject.toml
      

    container_name: main-app
    ports:
      - 8000:8000


  nginx-main:
    image: nginx
    volumes:
      - ./main/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 88:88
    restart: always
    depends_on: 
      - main

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    
    container_name: proxy-app
    ports:
      - 8010:8010
  
  nginx-proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    depends_on: 
      - proxy